### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mikkelsiggaard** [David-Lor/Docker-Signal-Desktop-GUI#3]
@David-Lor Is this still being maintained? 

I haven't been able to link this as a new device. 
QR code shows up, I scan it with my phone, I'm prompted to give it a name and that's how far I get.

**Comment by mikkelsiggaard** [comment]
<img width="1280" alt="image" src="https://github.com/David-Lor/Docker-Signal-Desktop-GUI/assets/23178730/62a21b29-c871-47f5-9607-dcb9be9bc96d">
<img width="1280" alt="image" src="https://github.com/David-Lor/Docker-Signal-Desktop-GUI/assets/23178730/b7053f84-e9d6-4533-9296-a8e7721fd114">

**Comment by David-Lor** [comment]
Sadly I'm no longer mantaining it as I'm no longer using this image, in fact I'm going to archive the repo. However, if you want to give it a try, you can try building the image yourself. It's probably not working because the Signal version is too old (image was build a year ago).
